### ISSUE TITLE
Unsupported

### ISSUE THREAD

**Issue by n0ne** [mironov/react-redux-loading-bar#1]
Hi.
I tryed to install and got this error:

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

Darwin?! My system not compatible with loading-bar... Sounds strange...

**Comment by mironov** [comment]
@n0ne Sorry, I accidentally included `npm-shrinkwrap.json` in the package that contains OS-specific dependencies. I just released the v1.1.1 without it.
Please try to install it and let me know if that works.

**Comment by n0ne** [comment]
Yes, now installed (-:
Thank you
