### ISSUE TITLE
Unallocated progressInterval handler

### ISSUE THREAD

**Issue by florin314** [mironov/react-redux-loading-bar#10]
I basically perform the actions bellow:

1) dispatch(showLoading())
2) dispatch(hideLoading())
3) dispatch(showLoading())
4) dispatch(hideLoading())
.....
Sometimes the error bellow pops up in an infinite loop:
window.console.error 
@ VM54:27printWarning 
@ warning.js:36warning 
@ warning.js:60
getInternalInstanceReadyForUpdate 
@ ReactUpdateQueue.js:48enqueueSetState 
@ ReactUpdateQueue.js:200ReactComponent.setState 
@ ReactComponent.js:64resetProgress 
@ loading_bar.js:104

I think that the resetProgress() from the 2) dispatch gets called after launch() function from 3) dispatch which overrides this.state.progressInterval.

A workaround/fix I did was to modify   resetProgress:
resetProgress() {
if (this.state.progressInterval) {    
  clearInterval(this.state.progressInterval);      
}
this.setState(initialState);   
}

**Comment by mironov** [comment]
@florin314 Thanks for reporting! This is fixed in v2.3.2.
