### ISSUE TITLE
Percent value isn't reset when animationTimeout is cleared

### ISSUE THREAD

**Issue by florin314** [mironov/react-redux-loading-bar#11]
Thank you for your quick answers on the previous issues.

When the animationTimeout is cleared on the launch function the percent isn't reset to 0 , so on the next showLoading action  the bar isn't displayed.
I put bellow a workaround that seems to solve this:

function launch() {
var progressInterval = this.state.progressInterval;
var animationTimeout = this.state.animationTimeout;
var percent = this.state.percent;

if (!progressInterval) {
  progressInterval = setInterval(this.boundSimulateProgress, this.props.updateTime);
  clearTimeout(animationTimeout);
  percent = 0;
}

this.setState(_extends({}, this.state, { progressInterval: progressInterval }, {percent: percent}));
}

**Comment by mironov** [comment]
@florin314 Thank you for your reports! Your suggestion works for me.
Fixed in v2.3.3.
