### ISSUE TITLE
set background color via className

### ISSUE THREAD

**Issue by oluckyman** [mironov/react-redux-loading-bar#12]
Now I see the only way to override background color is by setting `style` prop. But I would like to use `className` prop only and configure style in sass. To override background I have to use `!important` which makes my sass linter unhappy

**Comment by mironov** [comment]
@oluckyman Thanks for the detailed explanation. I agree, that needs to be improved. Setting the color for the Loading Bar should be as simple as possible.

I'll come with some solution this week.

**Comment by mironov** [comment]
@oluckyman Pushed the v2.4.0 that doesn't apply styling if you set a CSS class on the component. If you specify a CSS class, please set `color`, `height` and `position` yourself.
