### ISSUE TITLE
CreateSlice Redux

### ISSUE THREAD

**Issue by DenysSergeev** [mironov/react-redux-loading-bar#129]
Hello! Thank you for your **react-redux-loading-bar** library!

I'm new in React and Redux and I need to create state with Redux CreateSlice, **can you help me PLEASE!**

**Comment by mironov** [comment]
Hi there. I'm glad to hear that you're finding the `react-redux-loading-bar` library useful!

While I'm happy to assist with issues pertaining to the loading bar, I'd like to clarify that I am not a maintainer of the `redux`. You might want to consider reaching out to the maintainers of the `redux` or check out the official `redux` documentation.
