### ISSUE TITLE
Possible to add option to export UI component separately ?

### ISSUE THREAD

**Issue by RakanNimer** [mironov/react-redux-loading-bar#13]
Hey ! 
Thanks for your work on this cool module.

I'm trying to run some tests on a dumb component that is used to render the LoadingBar. 

I can't run tests on the UI part only as I can't import it separately because you're connecting to the store in the loading bar file and exporting the container.

Would it be possible to split the logic of connecting to store and rendering, and therefore allowing the user the option to import the smart connected component or the ui component and manage state herself ?

Leaving the connected as a default makes complete sense, it would just be cool to be able to import the dumb component.

Happy to submit a PR if you're interested ! 

Cheers !

**Comment by RakanNimer** [comment]
Yay :) Thanks !

**Comment by mironov** [comment]
@RakanNimer Hey, thank you for giving `react-redux-loading-bar` a try!
I pushed v2.3.4 that exports the UI component along with the container.
You can import it by name:
```js
import { LoadingBar } from 'react-redux-loading-bar'
```
