### ISSUE TITLE
Force hide loading

### ISSUE THREAD

**Issue by OmriKeret** [mironov/react-redux-loading-bar#19]
Hi guys,

Thanks for the work you've done with the react-redux-loading-bar.
I am using react-redux-loading-bar without a middleware and I found myself in need for "force hide loading bar" functionality.
Meaning I need the ability to hide the loading bar with no consideration to how many times SHOW has been dispatched.
Do you plan on developing this ability? 
Thanks

**Comment by mironov** [comment]
Hey @OmriKeret, I just published the v2.6.0 with the new `resetLoading` action. You can import it and dispatch wherever you want to "force hide" the loading bar. Thanks for the idea!

**Comment by OmriKeret** [comment]
Thanks!<3
