### ISSUE TITLE
error in isomorphic app 

### ISSUE THREAD

**Issue by royroev** [mironov/react-redux-loading-bar#2]
/Users/admin/WebstormProjects/chefmarket/node_modules/fbjs/lib/invariant.js:38
      error = new Error(format.replace(/%s/g, function () {
              ^
Invariant Violation: React DOM tree root should always have a node reference.

**Comment by mironov** [comment]
@royroev Could you include your `package.json` and the code you're using?
I just installed Loading Bar into an isomorphic app and it seems to be working:
https://github.com/mironov/isomorphic-redux-app/commit/3b64de76d1b3895e20b8c9e21d53e172520e7eaf

**Comment by 18601673727** [comment]
I have similar error with @royroev 
```
/Users/xxx/react-webpack-node/public/assets/server.js:694
	    throw error;
	    ^

Invariant Violation: React DOM tree root should always have a node reference.
```

**Comment by royroev** [comment]
@mironov i use last version https://github.com/kriasoft/react-starter-kit

**Comment by royroev** [comment]
@mironov oh, in the 2.0.0 version, all is well! Thanks )

**Comment by royroev** [comment]
no) work if 
```
class Header extends Component {
  componentDidMount() {
    this.setState({enableLoader: true})
  }
  render () {
    return (
      <div className={s.root}>
        {this.state.enableLoader ? <LoadingBar style={{backgroundColor : "rgba(17, 72, 29, 0.66)", zIndex : 223}} /> : null}
        <HeaderInfo className={s.info} />
        <Navigation className={s.nav} />
      </div>
    );
  }
  state = {
    enableLoader : false
  }

}

export default withStyles(s)(connect()(Header));
```

**Comment by mironov** [comment]
@royroev @18601673727 Thanks for the additional info.
I've released the v2.0.1 that should address the issue with isomorphic apps.
Please give it a try.

**Comment by royroev** [comment]
@mironov it's work! Thanks!

**Comment by 18601673727** [comment]
Sorry, not working for me, I'm sure configuration did well and no error occured just nothing happen.

You could reproduce by 
```
git clone https://github.com/18601673727/react-webpack-node
```
and change 
```
import LoadingBar from 'components/LoadingBar';
```
 to 
```
import LoadingBar from 'react-redux-loading-bar';
```
 in `app/containers/App.jsx`

**Comment by mironov** [comment]
@18601673727 Please use the bundled reducer instead of the `reducers/loading`.
This commit seems to be working: https://github.com/mironov/react-webpack-node/commit/2f08412fb67db10e2e5e3d928d769004faaaa818

**Comment by 18601673727** [comment]
@mironov Solved, that's the exact reason why it doesn't work, thank you!
