### ISSUE TITLE
Add support for react-redux 5.x

### ISSUE THREAD

**Issue by larrydahooster** [mironov/react-redux-loading-bar#20]
A new redux version was just released. I think the API is backward compatible and thus it should be no problem to add redux 5.x also to the peer dependency of this package.

**Comment by larrydahooster** [comment]
@mironov are there any future plans for this project? Or should I continue working on my own fork?

**Comment by mironov** [comment]
@larrydahooster Sorry guys I was offline for quite some time. I'll catch up on pending PRs and issues in upcoming days.

**Comment by mironov** [comment]
@larrydahooster Published 2.6.1 on the npm with the support for `react-redux` 5.x.
Thank you for the pull request!
