### ISSUE TITLE
Not sure if shouldShow is neccecary

### ISSUE THREAD

**Issue by stewartcelani** [mironov/react-redux-loading-bar#23]
For my personal use I found that if a page loaded really quickly and say percent was only at 30% when I called hideLoading() then the loading bar would fade out too quick before reaching the end and giving an appearance of it just disappearing.

Since width of the bar is tied to loading percentage (and wont be visible when loading = 0 in the redux store) I removed the shouldShow section from your render method so its just const style = this.buildStyle() before returning and now it behaves properly and animates to end before disappearing (width gets set to 0) when percent gets set to 100 via hideLoading().

I thought perhaps the shouldShow is intentional for use cases unlike mine but thought I'd let you know. Cheers.

EDIT: Oops. Just realised removing it completely causes the animation back to 0 to be visible. This achieves what I was after:

```
        const shouldShow = this.props.loading > 0 || this.props.loading == 0 &&  this.state.percent > 0
        if (shouldShow) {
            style.opacity = '1'
        } else {
            style.opacity = '0'
        }
```

**Comment by mironov** [comment]
@stewartcelani Could you arrange a quick test or a demo for that?

**Comment by mironov** [comment]
@stewartcelani I took the demo page of `react-redux-loading-bar` and tried 2 versions of the `shouldShow` calculation. I set the throttling to "Regular 4G" to get the loading bar middleware to call `hideLoading` at ~30 percent.

This is the original version: http://d.pr/v/xPW3
This is the version with proposed changes: http://d.pr/v/WVo0

I think the original version feels more natural and the proposed changes would keep Loading Bar visible on its way back to the initial state.

Please let me know if you think we should calculate `shouldShow` differently. I'm going to close the issue for now.
