### ISSUE TITLE
How to config store applyMiddleware with sagaMiddleware and loadingBarMiddleware

### ISSUE THREAD

**Issue by nguyenchanhnghia** [mironov/react-redux-loading-bar#24]
please tell me solution to this issues!

**Comment by mironov** [comment]
@nguyenchanhnghia You can pass both middlewares to the `applyMiddleware`:
```js
const store = createStore(
  rootReducer,
  applyMiddleware(sagaMiddleware, loadingBarMiddleware())
)
```

The `loadingBarMiddleware` monitors all actions, shows the loading bar on actions ending with "_PENDING" and hides the loading bar on actions ending with "_FULFILLED" or "_REJECTED".

The example for such saga might be:
```js
export function* fetchChannels() {
  try {
    const payload = yield call(fetchGraphQL, fetchChannelsQuery)
    yield put({ type: `${FETCH}_FULFILLED`, payload })
  } catch (error) {
    yield put({ type: `${FETCH}_REJECTED`, message: error.message })
  }
}

function* channelsSaga() {
  yield* takeEvery(`${FETCH}_PENDING`, fetchChannels)
}
```

If you dispatch a `${FETCH}_PENDING` action, both saga middleware and loading bar middleware will do their work.

Hope that helps. Please feel free to reopen the discussion if needed.

**Comment by nguyenchanhnghia** [comment]
@mironov thanks for support! I did it.

**Comment by mikedevita** [comment]
@mironov awesome explanation, i assume this would work similarly with thunks, pending that actions such as the REQUEST_PENDING, REQUEST_FULFILLED, REQUEST_REJECTED are used when fetching backend data...

**Comment by vrpruthvi** [comment]
@mironov I have implemented the above steps and found loading bar to visible for first dispatch action but doesn't show up for consecutive dispatch on the same route. I'm I missing something in declarations?

**Comment by mironov** [comment]
@vrpruthvi Could you post somewhere the log of actions dispatched? Do you use `loadingBarMiddleware`?

**Comment by vrpruthvi** [comment]
@mironov Yes, I'm using `loadingBarMiddleware`. Here is the action dispatch flow.
![action flow](https://cloud.githubusercontent.com/assets/5886080/25221008/3861241c-25d1-11e7-8221-7aa7dcb0af79.png)

**Comment by mironov** [comment]
@vrpruthvi Thank you for posting the screenshot.
It looks like the Loading Bar dispatches the `SHOW` and `HIDE` actions twice. That is correct because you have 2 `FETCH` actions here.

Could it be that you don't see the Loading Bar because the data comes really fast?
Try to pass the `showFastActions` prop to the Loading Bar:
```js
<LoadingBar showFastActions />
```

**Comment by vrpruthvi** [comment]
@mironov `FETCH` takes 1-2 secs. Tried using `showFastActions` still no luck.

**Comment by mironov** [comment]
@vrpruthvi Please check that Loading Bar is mounted on the page. Could it be that it unmounts after the first `FETCH`?

**Comment by vrpruthvi** [comment]
@mironov Yes Loading Bar is mounted on the page. Observed that state of component changes but still the bar doesn't show up on the page. When I traverse to other routes it works well for first dispatch and then doesn't show up for later dispatch.

![loadingbar](https://cloud.githubusercontent.com/assets/5886080/25225310/9c984854-25de-11e7-80ac-58db74d9545e.gif)

**Comment by mironov** [comment]
@vrpruthvi Well, that means that Loading Bar is simply not visible in the viewport. Probably another component renders on top of Loading Bar, or you have scrolled below it.

Check your CSS classes and try to increase `z-index`.

**Comment by vrpruthvi** [comment]
@mironov My bad! CSS was the culprit.
