### ISSUE TITLE
loading bar not hiding once displayed !!!

### ISSUE THREAD

**Issue by ashwinimnnit** [mironov/react-redux-loading-bar#28]
HI,  I have used loading bar as a middle ware. everything is working fine but one loading bar is displayed it is not hiding..

**Comment by mironov** [comment]
@ashwinimnnit Could you provide more info about your setup? Do you dispatch `_FULFILLED` or `_REJECTED` actions at the end of async events?

**Comment by ashwinimnnit** [comment]
yes I have dispatched _FULFILLEd or _REJECTED action the `loadingBarReducer` is executing and in `case HIDE` i'm getting newstate = 1. actually on page load there are several ajax call executing

**Comment by mironov** [comment]
@ashwinimnnit Please make sure the you call `_FULFILLED` or `_REJECTED` the same amount of times as `_PENDING`. Basically speaking, the Loading Bar will be shown until all ajax request complete.

If you want to forcefully hide Loading Bar, you can call `resetLoading()` at any time.

**Comment by ashwinimnnit** [comment]
I tried `resetLoading()`  but it is throwing error `Uncaught (in promise) TypeError: (0 , _reactReduxLoadingBar.resetLoading) is not a function`

**Comment by mironov** [comment]
Please show me the code you're using.

**Comment by ashwinimnnit** [comment]
`import { showLoading, hideLoading, resetLoading } from 'react-redux-loading-bar';

export default function loadingBarMiddleware(config = {}) {
    return (store) => next => (action) => {
        console.log('dispatch', action);

        const isPending = new RegExp(`_FETCHING_`, 'g')
        const isFulfilled = new RegExp(`_FETCHED_`, 'g')
        const isRejected = new RegExp(`_FETCH_.*_FAILED`, 'g')


        if (action.type.match(isPending)) {
            store.dispatch(showLoading())
        } else if (action.type.match(isFulfilled) ||
            action.type.match(isRejected)) {
            store.dispatch(hideLoading())
//             store.dispatch(resetLoading())

        }

        return next(action);
    }
}`  from here I'm dispatching the actions..

**Comment by mironov** [comment]
@ashwinimnnit Well, apparently I forgot to export `resetLoading` action. I just published the v2.6.5, please give it a try.

**Comment by ashwinimnnit** [comment]
ok :)

**Comment by ashwinimnnit** [comment]
Yeah that error has gone... but still hideLoading is not hiding the loading bar

**Comment by mironov** [comment]
Could you check what is in the store?

**Comment by ashwinimnnit** [comment]
@mironov : but show and hide action are executing same number of time...
 
I debug it ... in the end I'm getting  newState = 1 when `case is Hide`

**Comment by ashwinimnnit** [comment]
@mironov i checked store and get `loadingBar: 2`

**Comment by mironov** [comment]
`resetLoading` explicitly sets the counter to 0.
If the counter is > 0 that might mean that `showLoading` has been called after `resetLoading`.

Could you check the order of actions that were dispatched using redux logger middleware?

**Comment by ashwinimnnit** [comment]
Yeah sequence is somethig like this.

 loading-bar/SHOW ---> loading-bar/HIDE ---> loading-bar/SHOW --->   loading-bar/HIDE and at last newState is 1

**Comment by mironov** [comment]
In that case the counter should be 0. Please make sure there're no more loading bar related actions dispatched.

**Comment by ashwinimnnit** [comment]
when the first time showLoading() is called  `loadingBar: 2` in store , I think it should be 1

**Comment by mironov** [comment]
Yes it should be 1. Please check your initial state of the store when the app is being loaded.

**Comment by ashwinimnnit** [comment]
initially the state is 0 ---> then it become 1 ---> then  `loading-bar/SHOW` action executes which makes it 2.

**Comment by mironov** [comment]
When you say "then it become 1" — what do you mean? What action makes the counter to become 1?

**Comment by ashwinimnnit** [comment]
![logger](https://cloud.githubusercontent.com/assets/11703081/22334404/af76ab20-e400-11e6-93d8-ccea43615ce9.jpg)
 see my logger state

**Comment by mironov** [comment]
@ashwinimnnit Something is changing the counter to 1 before `showLoading` kicks in. I can take a look deeper if you can push related code to a repo or gist.

**Comment by ashwinimnnit** [comment]
Hi I debug the `loadingBarReducer() in loading_bar_duck` and found this 
![logger](https://cloud.githubusercontent.com/assets/11703081/22336667/025de22e-e409-11e6-8660-cc38f39a4784.jpg)

**Comment by mironov** [comment]
@ashwinimnnit Do you use the bundled `loadingBarReducer` or a custom one? It looks like the `loadingBarReducer` returns 1 on store initialization.

**Comment by ashwinimnnit** [comment]
Loading BarReducer is bundle but the middle ware is custom

On 26 Jan 2017 11:11 pm, "Anton Mironov" <notifications@github.com> wrote:

@ashwinimnnit <https://github.com/ashwinimnnit> Do you use the bundled
loadingBarReducer or a custom one? It looks like the loadingBarReducer
returns 1 on store initialization.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mironov/react-redux-loading-bar/issues/28#issuecomment-275456488>,
or mute the thread

**Comment by ashwinimnnit** [comment]
@mironov :
       
          function loadingBarReducer() {
             var state = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : 0;
           // here at store initialization arguments[0] contains 1 when the action type is                    @@redux/PROBE_UNKNOWN_ACTION_9.o.0.b.b.5.1.k.b.6.7.k.q.0.8.u.x.r 
            var action = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
    
           var newState = void 0;
          switch (action.type) {
            case SHOW:
            newState = state + 1;
             break;
            case HIDE:
            newState = state > 0 ? state - 1 : 0;
            break;
           case RESET:
            newState = 0;
            break;
           default:
        return state;
       }

  return newState;
}

**Comment by mironov** [comment]
@ashwinimnnit Could you show your `combineReducers` function?
