### ISSUE TITLE
Handle fast request

### ISSUE THREAD

**Issue by Chaoste** [mironov/react-redux-loading-bar#29]
Hi,

I'm using your module for my API request and I'm facing a problem right now. Often the request are very fast - let's say 5 ms (right now the server is running on localhost). For those request you want even the see the loading bar.

I would appreciate to see the bar quickly moving towards 100% and then disappearing. I guess this can be easily implemented by just adding a property "transitionTime" or something similar. So if the hide function is triggered, it sets the loading width to 100% while slowly disappearing.

For testing this behaviour, you could just call show() and hide() directly behind each other. The users should see something - if it's only for a very short timespan.

Right now I'm trying to add a nice feature to your loading bar for my project. If the server request was successful the bar should become green shortly before disappearing. Otherwise it becomes red - maybe it doesn't disappear directly.

Example for a nice implementation: http://chieffancypants.github.io/angular-loading-bar/#

Thank you for your work,
Thomas

**Comment by mironov** [comment]
Hey @Chaoste, sorry for the radio silence.
I pushed v2.7.0 with slightly reworked animation.
It will briefly display Loading Bar for quick actions as you requested.

**Comment by mironov** [comment]
@Chaoste Just a heads up that the behavior changed in v2.8.0.
The default behavior in v2.8.0 is to not show Loading Bar on fast actions.
If you want to display Loading Bar even on quickly finished actions you can pass the `showFastActions` prop.
