### ISSUE TITLE
setState() called on an unmounted component if change path after success action

### ISSUE THREAD

**Issue by stanislav-grin** [mironov/react-redux-loading-bar#3]
If you call `browserHistory.push(somepath)` after success action was dispatched, the next error would be:
`setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component`

Clearing interval in componentWillUnmount would resolve this issue. 
I've added this in `loading_bar.js` and it helped me:
```
{
    key: 'componentWillUnmount',
    value: function componentWillUnmount() {
      var interval = this.state.interval;
      var percent = this.state.percent;
      clearInterval(interval);
      interval = null;
      percent = 0;
    }
  }
```

**Comment by mironov** [comment]
@stanislav-grin Thanks for reporting that and for the solution!
Release v2.0.2 addresses the issue.
