### ISSUE TITLE
the bar keep reloading forever

### ISSUE THREAD

**Issue by oluckyman** [mironov/react-redux-loading-bar#31]
in 2.6.6. it works well, but in 2.7.0. it reloads forever

![fxmbur6bdu](https://cloud.githubusercontent.com/assets/642673/23252750/44992b30-f9b2-11e6-93e5-f71b0a1dbf1f.gif)

**Comment by vhpoet** [comment]
yep, I have the same [here](https://github.com/mironov/react-redux-loading-bar/issues/30).

**Comment by mironov** [comment]
@oluckyman Couple of questions:
1. Do you use server-side rendering?
2. Could you send me a list of redux actions and their order. This can be viewed with [`redux-logger`](https://github.com/evgenyrodionov/redux-logger) middleware.

**Comment by oluckyman** [comment]
I do not use server-side rendering.
I do not remember the specific order, but I know for sure that there are no any actions when the bar is hanging in the endless cycle of rerendering.

**Comment by mironov** [comment]
@oluckyman I just published the v2.7.1 that might fix the problem described. Please give it a spin and let me know how it goes.

**Comment by oluckyman** [comment]
it goes great, thanks! 👍
