### ISSUE TITLE
timeout until the loading bar is shown

### ISSUE THREAD

**Issue by naltatis** [mironov/react-redux-loading-bar#33]
Would be nice if it was possible to set an activation timeout. So that for fast actions (say under 300ms) the loading bar should not activate at all. This would make the UI less noisy in many cases.

**Comment by mironov** [comment]
@naltatis Good idea. The default behavior in v2.8.0 is to not show Loading Bar on fast actions.
If you want to display Loading Bar even on quickly finished actions you can pass the `showFastActions` prop.

**Comment by naltatis** [comment]
Nice 🚀! Thanks for your work, I'll try that tomorrow.
