### ISSUE TITLE
Can't make it work with redux-thunk

### ISSUE THREAD

**Issue by nextofsearch** [mironov/react-redux-loading-bar#34]
Hi, 

I followed the readme but can't make it work with redux-thunk.

```
import { routerReducer as routing } from 'react-router-redux'
import { combineReducers } from 'redux'
import { loadingBarReducer } from 'react-redux-loading-bar'

const rootReducer = combineReducers({
  routing,
  loadingBar: loadingBarReducer,
});

export default rootReducer;
```

```
import { createStore, applyMiddleware } from 'redux';
import thunk from 'redux-thunk'
import { logger } from 'redux-logger'
import rootReducer from '../reducers'
import { loadingBarMiddleware } from 'react-redux-loading-bar'

export default function configureStore(preloadedState) {
  const store = createStore(
    rootReducer,
    preloadedState,
    applyMiddleware(thunk, loadingBarMiddleware(), logger)
  );
  return store;
}

```

Also added `<LoadingBar />
`
Can you please tell me where to look?

**Comment by mironov** [comment]
@nextofsearch Hi.

In order to use `react-redux-loading-bar` with `redux-thunk` you'll need to dispatch `showLoading` and `hideLoading` actions from within your actions.

Your actions should look like that:

```js
import { showLoading, hideLoading } from 'react-redux-loading-bar'

function incrementAsync() {
  return dispatch => {
    dispatch(showLoading())
    setTimeout(() => {
      dispatch(increment());
      dispatch(hideLoading())
    }, 1000);
  };
}
```

**Comment by nextofsearch** [comment]
Hi @mironov 

Oh, I thought redux-thunk is one of middleware using Promises middleware. I just want to avoid adding showLoading() & hideLoading() to every action. What would be your recommendation of easy-to-use middleware choice?

Thanks!

**Comment by mironov** [comment]
@nextofsearch I've been using [`redux-promise-middleware`](https://github.com/pburtchaell/redux-promise-middleware) for quite a while. It's great and works out-of-the-box with `react-redux-loading-bar`.

**Comment by nextofsearch** [comment]
@mironov Thank you. I will try it out.

**Comment by jamby** [comment]
@nextofsearch Did you figure out a way to get it to work with `redux-thunk` and `redux-promise-middleware`? I also do not want to call `dispatch(showLoading())` and `dispatch(hideLoading())` every time. I would rather any AJAX request turns it on.

**Comment by mironov** [comment]
@jamby How do you perform AJAX requests? If you use `redux-promise-middleware` and `fetch`, then `react-redux-loading-bar` will work out of the box. You'll need to install the `loadingBarMiddleware` as it is mentioned in [Readme](https://github.com/mironov/react-redux-loading-bar#usage).

**Comment by jamby** [comment]
Currently using `redux-thunk` and then doing an `axios` request for posting/getting information.

For instance:

```javascript
return (dispatch) => {
    axios({
      method: 'get',
      url: '/api/data',
    }).then(({ data }) => {
      dispatch(setData(data));
    }).catch((error) => {
      console.log(error.response);
    });
  };
```

**Comment by mironov** [comment]
@jamby Sorry for the late reply.
I created a branch of demo with `axios`. You can take a look at the diff here:
https://github.com/mironov/react-redux-loading-bar/compare/gh-pages...demo-axios

**Comment by nextofsearch** [comment]
@jamby I haven't figured it out yet.
@mironov I am using thunk and 'isomorphic-fetch'. Is there any workaround for me as you suggested in the demo link above.

My custom fetching code is:

```
import fetch from 'isomorphic-fetch'

export function fetchData (url, beforeActionCreator, successActionCreator, failureActionCreator, options = {}) {

  return dispatch => {
    if(beforeActionCreator) {
      dispatch(beforeActionCreator())
    }

    return (
      fetch(url, requestOptions).
      then(checkStatus).
      then(parseJSON).
      then(json => dispatch(successActionCreator(json))).
      then(() => {
        if(typeof(successCallback) === 'function') {
           successCallback()
        }
      }).
      catch(error => {
        console.log('error', error)
        let promise = error.response.json().
                                     then(json => dispatch(failureActionCreator(json.message)))

        if(typeof(failureCallback) === 'function') {
          failureCallback(error)
        }

        return promise
      })
    )
  }
```

**Comment by jamby** [comment]
At first I was confused on how it works especially for chaining dispatches, but then I looked at the complex redux-promise-middleware demo and saw how they did it.

https://github.com/pburtchaell/redux-promise-middleware/tree/master/examples/complex

Thanks!

**Comment by mironov** [comment]
@nextofsearch It seems that you don't use `redux-promise-middleware` and thus can't [rely](https://github.com/mironov/react-redux-loading-bar/blob/master/src/loading_bar_middleware.js) on its action type names.

Do you use `fetchData` across the app whenever you need to fetch any data? If yes, you can simply put `showLoading` and `hideLoading` calls in it.
You can dispatch `showLoading` before dispatching `beforeActionCreator` and `hideLoading` before `successActionCreator ` and `failureActionCreator `.

I'm going to close the issue because that is not an issue with the lib. Feel free to use the issue to discuss the usage of the lib with `redux-thunk`.

**Comment by nextofsearch** [comment]
@mironov 
Thanks for the tip and it's working now.

**Comment by jasan-s** [comment]
@jamby  did you figure out how to use the middleware with axios and thunk ?
