### ISSUE TITLE
How to make loading bar loops

### ISSUE THREAD

**Issue by nextofsearch** [mironov/react-redux-loading-bar#35]
Hi,

I am wondering if I can make loading bar move in a loop until the components finishes loading. When  there are multiple long running fetches, the current implementation makes me wonder if it hung. 

Thank you!

**Comment by mironov** [comment]
@nextofsearch Sorry but that is not possible in the lib.
Loading bar is designed to simulate progress and not just as a loading indicator.
You can decrease `progressIncrease` to `3` or even `1` to make the progress slower.
