### ISSUE TITLE
Hideloading not hiding the progress bar

### ISSUE THREAD

**Issue by ksngits** [mironov/react-redux-loading-bar#38]
Hi,

I am using showLoading and hideLoading with redux forms. On successful form submission and return results, I am hiding the bar, but the loading bar is not getting hidden.

```
simpletask (values) 
  {
      const {reset} = this.props
      this.props.dispatch(showLoading())
      return promise_returned(values.nPassword)
          .then(function(){
            this.props.dispatch(hideLoading())  **>> this hideLoading is not working**
            reset();
          })
          .catch( function(err){
              this.props.dispatch(hideLoading())  
              throw new SubmissionError({ _error: err.message })
            }
        );
  }
```
The state keeps getting appended
**Object {form: Object, loadingBar: 1} (for first time)**
In fact my other forms are all working fine with redux-forms and following the same pattern. Let me know if i am required to provide further info

**Comment by ksngits** [comment]
huh, I know whats the issue..... arrow function & this ... leaving the answer for others to learn.

**Comment by mironov** [comment]
@ksngits Glad it worked out for you and thanks for posting the solution!
