### ISSUE TITLE
Showing bar for custom width fails

### ISSUE THREAD

**Issue by iphonic** [mironov/react-redux-loading-bar#42]
First of all, thanks for the plugin it works well, though I am finding some issues while it displays with added margin, see the screenshot below

![2017-06-15_16-05-10](https://user-images.githubusercontent.com/5745637/27177741-0c7384d6-51e5-11e7-843c-b4eb56633240.png)

What is happening is, I have a top nav bar in which I have added the Loader component which is supposed to show the loader from left 60px of the top bar, for this I have added `marginLeft:60px` which works well it starts leaving 60px from left, but when it finishes it crosses the header tag and goes beyond limit, see the screenshot which cause scroll bars to come up in the page.

Below is my code of **Loader**

```
const Loader = () => {
  return (
    <header style={{height:'3px',marginTop:'15px',marginLeft:'60px'}}>
      <LoadingBar style={{ backgroundColor: 'red', height: '3px', zIndex:9999, width:'100%', paddingRight:'60px' }} showFastActions updateTime={500} />
    </header>
  );
};
```

I tried to manipulate the `width` to some random value from 100%, it did work the progress bar was limited to that, but this is not way it should work, the progress bar should never go beyond header..

Any solution?

Thanks.

**Comment by iphonic** [comment]
**Update**

I have added `position` css to both parent and child which seems to fix the problem but partially, see me code below

```
const Loader = () => {
  return (
    <header style={{height:'3px',marginTop:'13px',marginLeft:'60px',position:'relative'}}>
      <LoadingBar style={{ backgroundColor: '#4da1ff', height: '3px',position:'absolute', zIndex:9999, width:'100%'}} showFastActions updateTime={500} />
    </header>
  );
};
```

But it created another problem the progress bar doesn't complete 100%, see below how it looks

![2017-06-15_16-31-41](https://user-images.githubusercontent.com/5745637/27178557-5350d202-51e8-11e7-8afa-4b0c3dc2473d.png)

Thanks.

**Comment by iphonic** [comment]
I fixed the issue by supplying `maxProgress={100}` as property, found that the default maxProgress  value was set to 99, so the progress wasn't completing 1.

**Comment by mironov** [comment]
@iphonic Glad it worked out for you. The default `maxProgress` is set to 99% to show that the long-running action is still in progress. Once action is completed, the loading bar will come to 100% and disappear.

**Comment by iphonic** [comment]
@mironov Should I consider that `showLoading()` only executes upto 99% while `hideLoading()` finishes the last 1%?

**Comment by mironov** [comment]
@iphonic yes, exactly
