### ISSUE TITLE
TypeDefinition support? [help wanted]

### ISSUE THREAD

**Issue by wongjiahau** [mironov/react-redux-loading-bar#47]
I'm currently using typescript to write my react app, therefore I need to have the TypeDefinition file for this library so that I can use it. 
Are contributors going to write one for it?

**Comment by mironov** [comment]
@wongjiahau There are TypeScript definitions in [`index.d.ts`](https://github.com/mironov/react-redux-loading-bar/blob/master/index.d.ts). Do they work for you?

**Comment by wongjiahau** [comment]
Thanks, I will look at it soon

**Comment by mironov** [comment]
@wongjiahau I'm going to close the issue for now. Feel free to re-open it if the current TypeScript definitions missing something.
