### ISSUE TITLE
How to use loadingBarMiddleware with axios?

### ISSUE THREAD

**Issue by permadiwibisono** [mironov/react-redux-loading-bar#48]
How  to using loadingBarMiddleware with axios not promises?

**Comment by mironov** [comment]
@permadiwibisono Isn't `axios` use promises under the hood? Please take a look at this commit to have the feeling how to use loading bar with `axios`: https://github.com/mironov/react-redux-loading-bar/commit/8044ea63c792a8991ee2fd5efcb7972a4dbed0dd

**Comment by permadiwibisono** [comment]
@mironov it's automatically change type from 'photos/FETCH' to 'photos/FETCH_FULFILLED'?

**Comment by permadiwibisono** [comment]
ohh I see,  you use promiseMiddleware. Can I use promiseMiddleware too with axios? I never using this package before. I'll try. Thanks

**Comment by mironov** [comment]
@permadiwibisono that's right, you can use `promiseMiddleware` with `axios` for sure.

**Comment by mironov** [comment]
I'm going to close this issue because that is not an issue. Feel free to reopen it if https://github.com/mironov/react-redux-loading-bar/commit/8044ea63c792a8991ee2fd5efcb7972a4dbed0dd doesn't work for you.
