### ISSUE TITLE
Customizing progressbar with props

### ISSUE THREAD

**Issue by mehrdaad** [mironov/react-redux-loading-bar#52]
Hey, thanks for your efforts.  
Can we customize the progressbar like the color or direction of completion with props?  
I checked 
https://github.com/mironov/react-redux-loading-bar/blob/master/src/loading_bar.js#L189   
but seems like there isn't any way to customize.  

Also, Is there any to show a circular a progress bar like: http://ricostacruz.com/nprogress/ ? thanks.

**Comment by mironov** [comment]
@mehrdaad You can configure the color with `<LoadingBar style={{ backgroundColor: 'blue' }} />`.

The direction can be switched with `<LoadingBar style={{ transformOrigin: 'right' }} />`.

Unfortunately, there's no way to show a circle like `nprogress` does.

**Comment by mehrdaad** [comment]
@mironov what' your opinion about creating a pr and adding that feature?

**Comment by mironov** [comment]
@mehrdaad I'd accept the PR if it will be configurable via props i.e. doesn't break the current behavior with default props.

**Comment by mehrdaad** [comment]
Ok will work on it. How about creating a branch here? Or creating a pull request directly on this repo?

**Comment by mironov** [comment]
@mehrdaad Sounds good. You can fork the repo and submit a PR to this repo.
