### ISSUE TITLE
Loading Bar not showing up

### ISSUE THREAD

**Issue by rkrishn** [mironov/react-redux-loading-bar#53]
Hi  I am using react/redux with react-redux-loading-bar plugin here is my store and saga and UI component. Could any one tell what i am doing wrong here.

SAGA.js

```
const filterGetData = function* ( action ) {
  try {
    yield put(showLoading())
    const users = yield call(fetchUsers,action.payload);
    yield put({type: 'USERS_RECIEVED', users})
  } catch (error) {
  yield put({type: 'LOAD_USERS_FAILURE', error})
  }finally {
    yield put(hideLoading())
  }
};
export function* watchForUsers() {
  while(true) {
    const action = yield take('LOAD_USERS');
    yield fork(filterGetData, action);
  }
}
```

Index.js

```
const rootReducers = combineReducers({
  appReducer,
  loadingBar: loadingBarReducer,
})
const store = createStore(
  rootReducers,
  applyMiddleware(sagaMiddleware ,loadingBarMiddleware())
);
sagaMiddleware.run(watchForUsers);
```

Ui component

```
<header>
 <LoadingBar style={{zIndex: 99999}}/>
</header>
```

**Comment by mironov** [comment]
@rkrishn Could you post here what actions dispatched and in what order? You can see that with [`redux-logger`](https://github.com/evgenyrodionov/redux-logger) or [`Redux DevTools`](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en).

**Comment by rkrishn** [comment]
![capture](https://user-images.githubusercontent.com/16647331/33818012-af77c11e-de68-11e7-8f46-772b29fede43.PNG)

**Comment by rkrishn** [comment]
![image](https://user-images.githubusercontent.com/16647331/33818080-0050f6fa-de69-11e7-83ab-f0aa2449b1d1.png)

**Comment by rkrishn** [comment]
@mironov  attached the file with redux-logger please have a look

**Comment by mironov** [comment]
@rkrishn I can't think of anything off the top of my head. Could you publish a quick repository that reproduces the issue?

**Comment by rkrishn** [comment]
@mironov I have hosted the repo code in github please checkout my code.
https://github.com/rkrishn/github_user_search

**Comment by rkrishn** [comment]
@mironov solved the issue by passing loading prop for LoadingBar. But do we need to pass the loading prop from state ?

**Comment by mironov** [comment]
@rkrishn Passing the loading prop shouldn't be needed as it is pulled from the store by the connected Loading Bar component. It is exported via the default export.

https://github.com/rkrishn/github_user_search/blob/b43fed97ef6ee69f7c2db2921299f2b4d6fa53dc/src/components/App.js#L5

Looks like you're importing the bare UI component that doesn't connect itself to the store.
Please change the line to:
```
import LoadingBar from 'react-redux-loading-bar'
```

**Comment by rkrishn** [comment]
thanks @mironov its working now.

**Comment by mironov** [comment]
@rkrishn Thank you for the repository with the demo. It helped a lot.
