### ISSUE TITLE
props Children

### ISSUE THREAD

**Issue by diegoalmesp** [mironov/react-redux-loading-bar#58]
Hi! I was trying to attach another div to `<LoadingBar />` so that will block the component below. The idea is: when you click a button, after the dispatch I will lock the screen while showing the loading bar.

something like this.props.children will be usefull so I could do 

    <LoadingBar>
        <div block />
    </LoadingBar>

Do you have another approach to sugest? I also created a Loading component that will render:

    <div>
        <LoadingBar />
        <div block />
    </div>

But while the LoadingBar disappears when needed the div below doesn't

Thanks! and great work, very useful and easy to implement

**Comment by mironov** [comment]
Hi @diegoalmesp. Unfortunately, it is not possible to render custom HTML inside Loading Bar.

I'd suggest rendering some kind of Modal that will lock the screen and display the Loading Bar along with any additional HTML. You can dispatch an action on button click that will show the Modal and invoke loading bar's `showLoading()` action. Once the long-running action completes, you can hide the modal and the loading bar.

**Comment by mironov** [comment]
I'm going to close the issue. Feel free to reopen it if you have any question.

**Comment by diegoalmesp** [comment]
Thanks @mironov !
