### ISSUE TITLE
Object doesn't support this action

### ISSUE THREAD

**Issue by Razzwan** [mironov/react-redux-loading-bar#59]
But in IE: Object doesn't support this action, when trying `loading-bar/SHOW` action executed

**Comment by mironov** [comment]
@Razzwan Is the [demo](https://mironov.github.io/react-redux-loading-bar/) working for you? Which version of Internet Explorer are you using?

**Comment by mironov** [comment]
I'm going to close the issue because of inactivity. Feel free to reopen it.
I tested the demo in IE, and it worked for me. Need more info.
