### ISSUE TITLE
Promise middleware does not support 'scope' property

### ISSUE THREAD

**Issue by Reptarsrage** [mironov/react-redux-loading-bar#60]
The promise middleware [here](https://github.com/pburtchaell/redux-promise-middleware/blob/master/src/index.js)  does not support any custom properties on the action except for type, payload and meta. Therefore, this library's middleware should check for the scope property within the meta property of the action, not on the action itself.

**Comment by Reptarsrage** [comment]
You could change line 17 of  [loading_bar_middleware.js](https://raw.githubusercontent.com/mironov/react-redux-loading-bar/master/src/loading_bar_middleware.js) from:  
`const actionScope = action.scope || scope`  
to:  
`const actionScope = action.meta.scope || scope`

**Comment by mironov** [comment]
@Reptarsrage Thank you. This should be fixed in v3.1.2.
The previous behavior is retained for compatibility reasons.
