### ISSUE TITLE
Loading Bar not displayed

### ISSUE THREAD

**Issue by tripstar22** [mironov/react-redux-loading-bar#61]
Hi @mironov,

I am hoping you can help me solve an issue I am having with `react-redux-loading-bar`. I have installed the package and I created a component for `<LoadingBar />`. The component shows up when my app is loading (I can see my gradient overlay), however `LoadingBar` stays at `opacity: 0;` and `transform: scaleX(0)`.

Here is my code...

`LoadingBar` component:
```
import React from 'react';
import styled from 'styled-components';
import { ImmutableLoadingBar as LoadingBar } from 'react-redux-loading-bar';
import {
  InfoColor,
} from '../constants';

// styles for progress bar wrap
const WrapProgressBar = styled.div`
  width: 100%;
  height: 10px;
  position: absolute;
  top: 0;
  left: 0;

  header, header > div {
    width: 100%;
  }
`;

// styles for gradient overlay
const GradientOverlay = styled.div`
  background: rgba(57,56,54,0.8);
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  z-index: 99999;
`;

const ProgressBar = ({ fetching }) => (
  <WrapProgressBar fetching={fetching}>
    <header>
      <LoadingBar style={{ backgroundColor: InfoColor, height: '10px', opacity: '1', zIndex: '100000' }} />
    </header>
    <GradientOverlay />
  </WrapProgressBar>
);

export default ProgressBar;
```
Added reducer to store:
```
const appReducer = combineReducers({
    route: routeReducer,
    language: languageProviderReducer,
    loadingBar: loadingBarReducer,
    form,
    ...injectedReducers,
  });
```
Apply middleware: 
```
const store = createStore(
    createReducer(),
    fromJS(initialState),
    composeEnhancers(...enhancers),
    applyMiddleware(loadingBarMiddleware())
  );
```
`LoadingBar` component in app:
`{fetching && <ProgressBar fetching={fetching} />}`

Any help is appreciated. Thank you!

**Comment by mironov** [comment]
@tripstar22 Hi there. Am I right that you don't use any promise middleware and you will control the visibility of your `ProgressBar` by yourself using the `fetching` prop?

If that is true, I think you can import not connected `LoadingBar` component and mount it directly.
Something like this should work for you:
```js
import { LoadingBar } from 'react-redux-loading-bar';

# <...> removed styles for the purpose of brevity

const ProgressBar = ({ fetching }) => (
  <WrapProgressBar fetching={fetching}>
    <header>
      <LoadingBar loading={1} style={{ backgroundColor: InfoColor, height: '10px', opacity: '1', zIndex: '100000' }} />
    </header>
    <GradientOverlay />
  </WrapProgressBar>
);
```

You can also skip the `middleware` and `reducer` steps because they are needed to show/hide the loading bar automatically during long-running actions.

Please let me know if that helps.

**Comment by tripstar22** [comment]
@mironov thanks for the response. Yup you're correct about using the `fetching` prop. 

Seems to be working now so I will close this issue. Thanks again!

**Comment by hamza-jutt** [comment]
Hello! @mironov 
I've a similar issue. Loading bar is not being displayed.

Here is the store config. I'm using axios.
```
import promise from 'redux-promise';
import thunk from 'redux-thunk';
import {applyMiddleware, createStore, compose} from 'redux';
import { loadingBarMiddleware } from 'react-redux-loading-bar'


const store = createStore(
    reducers,
    compose(
        applyMiddleware(promise, thunk, loadingBarMiddleware()),
        window.devToolsExtension ? window.devToolsExtension() : f => f
   )
);
```
