### ISSUE TITLE
Creating an optimized production build... Failed to compile. after update to 4.0.2

### ISSUE THREAD

**Issue by saostad** [mironov/react-redux-loading-bar#62]
I am using Create-react-app to build my app, but after I update my react-redux-loading-bar package to 4.0.2 version I got error below:

> Creating an optimized production build...
> Failed to compile.
> 
> Failed to minify the code from this file:
> 
>         ./node_modules/react-lifecycles-compat/react-lifecycles-compat.es.js:64
> 
> Read more here: http://bit.ly/2tRViJ9

I am guessing if I downgrade my version to 4.0.0 it will work but I didn't test it yet.

**Comment by mironov** [comment]
@saostad Thank you for reporting this.
I pushed v4.0.3 that depends on the latest `react-lifecycles-compat`.
Could you give it a try?

I created a test repository with the latest `create-react-app` and `react-redux-loading-bar`: https://github.com/mironov/create-react-app-loading-bar

I don't see this error in the console:
```
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  46.74 KB  build/static/js/main.784eda5a.js
  299 B     build/static/css/main.c17080f1.css

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  serve -s build

Find out more about deployment here:

  http://bit.ly/2vY88Kr
```

**Comment by saostad** [comment]
Thanks
