### ISSUE TITLE
Redux 4.x.x support in package.json

### ISSUE THREAD

**Issue by jacekradko** [mironov/react-redux-loading-bar#64]
There was a new major version of Redux released recently [Changelog](https://github.com/reactjs/redux/releases). At first look it doesn't appear to contain any breaking changes. Any chance of updating the dependency in package.json  to `"redux": ">3.5.2"`?

**Comment by mironov** [comment]
@jacekradko Good idea. I released v4.0.4 with relaxed Redux dependency.
