### ISSUE TITLE
Uncaught TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by pak11273** [mironov/react-redux-loading-bar#69]
```
// test.js
import React, {Component} from 'react'
import LoadingBar from 'react-redux-loading-bar'

export default class Test extends Component {
     render() {
          return (
               <div>
                    <LoadingBar /> 
               </div>
           )
     }
}
```

// I'm getting this error in the console:
`Uncaught TypeError: Cannot read property 'default' of undefined`

![image](https://user-images.githubusercontent.com/2309184/41790534-7cd9f5e0-7618-11e8-998f-2e3f4fde4d30.png)

**Comment by mironov** [comment]
@pak11273 Have you [installed the reducer](https://github.com/mironov/react-redux-loading-bar#usage)?

```js
import { combineReducers } from 'redux'
import { loadingBarReducer } from 'react-redux-loading-bar'

const reducer = combineReducers({
  // app reducers
  loadingBar: loadingBarReducer,
})
```

**Comment by pak11273** [comment]
The reducer is installed.  I notice that you import loadingBarReducer with { } notation.  The docs do not reflect this, so which is correct?

**Comment by pak11273** [comment]
Yes the reducer is installed in the store.

**Comment by mironov** [comment]
@pak11273 Is your `Test` component wrapped in the `react-redux`'s [`Provider`](https://github.com/reduxjs/react-redux/blob/master/docs/api.md#provider-store) somewhere up in the DOM tree?

**Comment by pak11273** [comment]
Ah nvm.  The problem was this:

```
import { combineReducers } from 'redux'
import { loadingBarReducer } from 'react-redux-loading-bar'

const reducer = combineReducers({
  // app reducers
  loadingBarReducer,  // I DIDN'T RENAME THIS PROPERTY TO loadingBar
})
```

Sorry for any inconviences.
