### ISSUE TITLE
Complete animation on hideLoading

### ISSUE THREAD

**Issue by glekner** [mironov/react-redux-loading-bar#82]
Is there a way for the bar to complete the animation all way through (at one tick) once hideLoading has been called? Right now the bar just disappears
![loadingbar](https://user-images.githubusercontent.com/24938324/50572370-0d57f800-0dc8-11e9-8df6-b9744521d588.gif)

**Comment by mironov** [comment]
@glekner It should complete the animation on `hideLoading`. How do you mount Loading Bar? Do you pass any custom `updateTime`, `maxProgress`, `progressIncrease`.

**Comment by glekner** [comment]
@mironov nevermind the problem is at my end, the component gets unmounted on page switching due to rails backend.
