### ISSUE TITLE
How to use with react-router

### ISSUE THREAD

**Issue by kopax** [mironov/react-redux-loading-bar#84]
Hi everyone and thanks for sharing this,

I know redux well and react well, I understand that we can dispatch two actions to animate the loading bar.

I am using `react-router-dom@4.3.1` and `connected-react-router@6.1.0`, does anybody have a working well integration with react-router to purpose here?

Thanks in advance,

**Comment by kopax** [comment]
I am still trying to figure out how I can use this properly.

- What is the benefits of using `redux-promise-middleware` ?

I saw `React.Lazy` appear in React v16.6.

I see react recommend [loadable-components](https://github.com/smooth-code/loadable-components), I also see a similiar [react-loadable](https://github.com/jamiebuilds/react-loadable). 

I want to enable route chunking in webpack but I want to be able to have a top loading bar indicator. 

This means I want to lock the view while the next page is loading, I believe I should use one of those but I am not sure.

Is there one that would be the more appropriate for my use case?

**Comment by atefBB** [comment]
Hey @kopax ! I'm trying to integrate this package with `react-router-dom`, how did you solve this issue?
