### ISSUE TITLE
It does not render any classname nor interact with the store

### ISSUE THREAD

**Issue by kopax** [mironov/react-redux-loading-bar#85]
I've just tried to add `<LoadingBar />` in my app, it render a `<div></div>` with no class.

I have wrapped the div because it was completely impossible to use `style` `className` or `css` to customize the props.

        <div css={`
          & > div {
            height: 3px;
            background-color: red;
            position: absolute;
          }
        `}>
          <LoadingBar />
        </div>

Looking at redux store, it get populated on first dispatch but stays at 0.

**Comment by mironov** [comment]
@kopax How do you import `LoadingBar`? It should be imported from the default export in order to be connected to the store.

```js
import LoadingBar from 'react-redux-loading-bar'
```

You should be able to configure style by passing the `style` prop:
```js
<LoadingBar style={{ backgroundColor: 'red', height: '3px', position: 'absolute' }} />
```

**Comment by kopax** [comment]
Yes, we did like this. We also tried the immutable version. Both failed so we switch to another lib. Maybe it's our fault. Thanks for replying though.
