### ISSUE TITLE
resetProgress is called after the loading-bar was unmounted

### ISSUE THREAD

**Issue by florin314** [mironov/react-redux-loading-bar#9]
VM789:27 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component.

window.console.error	@	VM789:27
printWarning	@	warning.js:36
warning	@	warning.js:60
getInternalInstanceReadyForUpdate	@	ReactUpdateQueue.js:48
enqueueSetState	@	ReactUpdateQueue.js:200
ReactComponent.setState	@	ReactComponent.js:64
resetProgress	@	loading_bar.js:98

**Comment by mironov** [comment]
@florin314 Thanks for letting me know, this is fixed in v2.3.1.
