### ISSUE TITLE
Usage without redux

### ISSUE THREAD

**Issue by erkieh** [mironov/react-redux-loading-bar#91]
Would it be possible to use this without redux?

**Comment by mironov** [comment]
@erkieh Yes, you can import not connected component:
`import { LoadingBar } from 'react-redux-loading-bar'`

And mount it the following way:
```
<header>
  <LoadingBar loading="1" />
</header>
```

Please note that you will need to pass `loading` prop > 0 to show Loading Bar and = 0 to hide it.

**Comment by erkieh** [comment]
I was hoping to use it without having redux in my project at all. The import still runs the script and tries to create a connected component.

**Comment by mironov** [comment]
@erkieh Well, `redux` is a peer dependency and will always be. If you don't use `redux` at all, you might want to choose another pure react library.
